name: MK-Consulting
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6870976388454437
title: GER85 Sailingteam
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bbc6dc'
    - '#14171e'
    - '#676e78'
    - '#98a0b4'
    - '#e3dbd9'
  brandStrength: 0.125
  lightness: 0.689621037337929
  saturation: 0.4957500894088298
  rhythmicContrast: 0.900436251424253
purpose: []
